version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      python : 3.12
    commands:
      - echo "Install phase"
  build:
    commands:
      - codebuild-breakpoint
      - sam build
      - sam deploy --no-fail-on-empty-changeset
      - export WS_URL=$(aws cloudformation describe-stacks --stack-name trivia-app --query 'Stacks[0].Outputs[?OutputKey==`WebSocketURL`].OutputValue' --output text)      
      - cd front-end-react
      - npm install
      - npm run build
      - codebuild-breakpoint
      - aws s3 sync --acl public-read build/ s3://123456-abdullah-bucket/
