version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.12
    commands:
      - echo "Install phase"
  pre_build:
    commands:
      - cd front-end-react
      - if [ ! -f package-lock.json ]; then echo "package-lock.json not found"; exit 1; fi
  build:
    commands:
      - sam build
      - sam deploy --no-fail-on-empty-changeset
      - export WS_URL=$(aws cloudformation describe-stacks --stack-name trivia-app --query 'Stacks[0].Outputs[?OutputKey==`TriviaWebSocketApi`].OutputValue' --output text)      
      - echo "WS_URL=$WS_URL"
      - cd front-end-react
      - npm ci
      - echo "REACT_APP_WS_URL=$WS_URL" > .env
      - npm run build
      - aws s3 sync --acl public-read build/ s3://123456-abdullah-bucket/

cache:
  paths:
    - front-end-react/node_modules/**/*
    - /root/.npm/**/*
  key: 
    files:
      - front-end-react/package-lock.json
      - front-end-react/package.json
