
version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
      - pyenv install -s 3.7.10
      - pyenv global 3.7.10
  build:
    commands:
      - codebuild-breakpoint
      - sam build
      - sam deploy --no-fail-on-empty-changeset
      - cd front-end-react
      - npm install
      - npm run build
      - aws s3 sync --acl public-read build/ s3://123456-abdullah-bucket/